name: Bandit

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements*.txt"
      - "setup.cfg"
      - ".bandit"
      - "bandit.yaml"
      - "bandit.yml"
      - ".github/workflows/bandit.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.py"
      - "pyproject.toml"
      - "poetry.lock"
      - "requirements*.txt"
      - "setup.cfg"
      - ".bandit"
      - "bandit.yaml"
      - "bandit.yml"
      - ".github/workflows/bandit.yml"
  schedule:
    - cron: "37 14 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  bandit:
    name: Bandit scan → SARIF
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write
      actions: read

    env:
      BANDIT_VERSION: "1.8.6"
      SARIF_OUT: "reports/bandit.sarif"

    steps:
      - name: Harden the runner (Audit outbound egress)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      # NEW: Detect dependency files. If none exist, skip pip cache to avoid setup-python errors.
      - name: Detect dependency files for pip cache
        id: deps
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          files=( **/requirements*.txt **/pyproject.toml **/poetry.lock **/setup.cfg )
          if [ ${#files[@]} -gt 0 ]; then
            echo "have_deps=true" >> "$GITHUB_OUTPUT"
            {
              echo "paths<<EOF"
              printf '%s\n' "${files[@]}"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
            echo "Dependency files:"
            printf '  - %s\n' "${files[@]}"
          else
            echo "have_deps=false" >> "$GITHUB_OUTPUT"
            echo "No dependency files detected; will set up Python without pip cache."
          fi

      # Use pip cache only when dependency files exist (prevents the “No file matched” error).
      - name: Set up Python (with pip cache)
        if: ${{ steps.deps.outputs.have_deps == 'true' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: ${{ steps.deps.outputs.paths }}

      # Fallback: set up Python without cache when no dep files are present.
      - name: Set up Python (no cache)
        if: ${{ steps.deps.outputs.have_deps != 'true' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Install Bandit (pinned)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          python -m pip install "bandit[toml]==${BANDIT_VERSION}"
          bandit --version
        timeout-minutes: 3

      - name: Run Bandit and write SARIF
        run: |
          set -euxo pipefail
          mkdir -p "$(dirname "${SARIF_OUT}")"
          bandit -r . \
            --format sarif \
            --output "${SARIF_OUT}" \
            --severity-level all \
            --confidence-level all \
            --exit-zero \
            --quiet \
            --exclude .git,.venv,venv,.tox,site-packages,dist,build
        timeout-minutes: 5

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        with:
          sarif_file: ${{ env.SARIF_OUT }}
          category: bandit

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bandit-sarif
          path: ${{ env.SARIF_OUT }}
          retention-days: 14
