# OSV-Scanner (hardened, pinned) — PRs, merge queue, pushes to main, weekly, manual
# =============================================================================
# What this does:
#   • For PRs/merge-queue: runs OSV-Scanner to catch new vulns before merge.
#   • For pushes/scheduled: runs periodic scans for drift.
# Why this shape:
#   • Reusable workflow calls (required by OSV’s repo) → no local steps here.
#   • Least privilege: job-level permissions scoped to each call.
#   • Concurrency + timeouts; explicit branch/path filters; SHA pins.

name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
    paths:
      # Narrow to dependency manifests to save minutes. Add/remove as needed.
      - "**/package.json"
      - "**/package-lock.json"
      - "**/pnpm-lock.yaml"
      - "**/yarn.lock"
      - "**/requirements*.txt"
      - "**/pyproject.toml"
      - "**/poetry.lock"
      - "**/Pipfile.lock"
      - "**/go.mod"
      - "**/go.sum"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/pom.xml"
      - "**/build.gradle*"
      - "**/Gemfile.lock"
      - "**/composer.lock"
      - "**/mix.lock"
      - "**/*.csproj"
      - "**/*.fsproj"
      - ".github/workflows/osv-scanner.yml"

  merge_group:
    branches: [ "main" ]
    paths:
      - "**/*"
      - ".github/workflows/osv-scanner.yml"

  push:
    branches: [ "main" ]
    paths:
      - "**/*"
      - ".github/workflows/osv-scanner.yml"

  schedule:
    - cron: "18 6 * * 1"    # Mondays 06:18 UTC

  workflow_dispatch: {}

# Cancel superseded runs (prevents CI pile-ups on busy PRs)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Default-deny at workflow level; jobs elevate only what they need
permissions:
  contents: read

jobs:
  # ───────────────────────── Scheduled / Push scans ─────────────────────────
  scan-scheduled:
    # Reusable workflow call: you cannot add local steps here.
    # OSV’s reusable workflow handles checkout, scanning, and SARIF upload.
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    # Least privilege needed to upload SARIF
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 15
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@90b209d0ea55cea1da9fc0c4e65782cc6acb6e2e # v2.2.2
    with:
      # Scan recursively; skip .git
      scan-args: |-
        -r
        --skip-git
        ./

    # If your repository needs secrets (rare for OSV), pass them through:
    # secrets: inherit

  # ───────────────────────── PR / Merge-queue scans ────────────────────────
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    permissions:
      contents: read
      security-events: write
    timeout-minutes: 15
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@90b209d0ea55cea1da9fc0c4e65782cc6acb6e2e # v2.2.2
    with:
      scan-args: |-
        -r
        --skip-git
        ./
