name: OSV-Scanner

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/package.json"
      - "**/package-lock.json"
      - "**/pnpm-lock.yaml"
      - "**/yarn.lock"
      - "**/requirements*.txt"
      - "**/pyproject.toml"
      - "**/poetry.lock"
      - "**/Pipfile.lock"
      - "**/go.mod"
      - "**/go.sum"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/pom.xml"
      - "**/build.gradle*"
      - "**/Gemfile.lock"
      - "**/composer.lock"
      - "**/mix.lock"
      - "**/*.csproj"
      - "**/*.fsproj"
      - ".github/workflows/osv-scanner.yml"
  merge_group:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  schedule:
    - cron: "18 6 * * 1"
  workflow_dispatch: {}

# Cancel superseded runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Default-deny
permissions:
  contents: read

jobs:
  # ─────────────────────────────────── Scan ───────────────────────────────────
  osv-scan:
    name: OSV scan → SARIF
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    permissions:
      contents: read

    env:
      OSV_VERSION: v2.2.2
      SARIF_OUT: osv.sarif   # write to workspace root → no mkdir needed

    # Advertise whether a SARIF exists so the next job can decide to run
    outputs:
      has_sarif: ${{ steps.check.outputs.has_sarif }}

    steps:
      - name: Harden runner (egress audit)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Go (pinned)
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.23.x"

      - name: Install OSV-Scanner v2 (pinned)
        run: |
          echo "$HOME/go/bin" >> "$GITHUB_PATH"
          go install github.com/google/osv-scanner/v2/cmd/osv-scanner@${OSV_VERSION}
          osv-scanner --version

      # Keep scanning even if vulns are found so we can upload SARIF.
      - name: Run OSV-Scanner → SARIF
        continue-on-error: true
        run: |
          # v2 syntax: 'scan'; do not use '--skip-git'
          osv-scanner scan -r ./ --format sarif --output "${SARIF_OUT}"

      # Decide if we actually have a SARIF to publish
      - name: Check SARIF exists
        id: check
        shell: bash
        run: |
          if [[ -s "${SARIF_OUT}" ]]; then
            echo "has_sarif=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_sarif=false" >> "$GITHUB_OUTPUT"
          fi

      # Upload artifact only when the file exists (avoids later download errors)
      - name: Upload SARIF artifact
        if: always() && steps.check.outputs.has_sarif == 'true'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: osv-sarif
          path: ${{ env.SARIF_OUT }}
          retention-days: 14

  # ───────────────────────────────── Upload ──────────────────────────────────
  upload-sarif:
    name: Upload OSV SARIF to Code Scanning
    needs: osv-scan
    if: ${{ needs.osv-scan.outputs.has_sarif == 'true' }}  # only run if artifact exists
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Harden runner (egress audit)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Download SARIF artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: osv-sarif
          path: .

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        with:
          sarif_file: osv.sarif
          category: osv-scanner
