# OpenSSF Scorecard supply-chain security — compliant with Scorecard workflow restrictions
# =============================================================================
# What this workflow does:
#   1) Job "analysis" runs Scorecard and writes `results.sarif`.
#      IMPORTANT: this job contains ONLY `uses:` steps to satisfy Scorecard's verifier.
#   2) Job "upload-to-code-scanning" downloads that SARIF and uploads it to GitHub Code Scanning.
#
# Best practices:
#   • Default-deny permissions; job-level least privilege.
#   • SHA-pinned actions; explicit runner; concurrency; timeouts.
#   • Egress hardening (audit now; later block + allowlist).
#   • No `run:` steps in the Scorecard job.

name: Scorecard supply-chain security

on:
  branch_protection_rule:         # refresh Branch-Protection check when rules change
  schedule:
    - cron: '40 16 * * 1'         # weekly, tune to taste
  push:
    branches: [ "main" ]          # default branch (publishing supported only here)
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*"
      - ".github/workflows/scorecard.yml"

# Cancel superseded runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Default-deny
permissions:
  contents: read

jobs:
  # ────────────────────────────── Job 1: Scorecard analysis (uses-only) ──────────────────────────────
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    # Keep least privilege here. Scorecard publishing to OpenSSF needs id-token: write on default branch.
    permissions:
      contents: read
      id-token: write

    # This job MUST contain ONLY `uses:` steps to pass Scorecard's workflow verification.
    steps:
      - name: Harden runner (egress audit)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          # Later: switch to block + allowlist (api.github.com, uploads.github.com, github.com, objects.githubusercontent.com)

      - name: Checkout code (no persisted creds)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      # Scorecard writes `results.sarif`. `publish_results` is true only on default branch (public repos).
      - name: Run Scorecard
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          # Optional PAT for Branch-Protection on public repos or for private repos:
          # repo_token: ${{ secrets.SCORECARD_TOKEN }}
          # Optional: if your .gitattributes uses export-ignore
          # file_mode: git

      # Store SARIF for the next job and for auditing
      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: scorecard-sarif
          path: results.sarif
          retention-days: 14

  # ───────────────────────────── Job 2: Upload to Code Scanning (separate permissions) ─────────────────────────────
  upload-to-code-scanning:
    name: Upload Scorecard SARIF to Code Scanning
    needs: analysis
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    # Only this job can write security events
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Harden runner (egress audit)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Download SARIF artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: scorecard-sarif
          path: .

      - name: Upload to Code Scanning
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        with:
          sarif_file: results.sarif
          category: ossf-scorecard
