name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]

jobs:
  semgrep_scan:
    name: semgrep/ci
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep scan -q --config auto --sarif --output=semgrep.sarif .

      - name: Debug: List files
        run: ls -lah

      - name: Save SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif
          if-no-files-found: ignore

      - name: Upload SARIF to Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
