name: SonarCloud analysis

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Prepare reports directory and compile_commands.json
        run: |
          mkdir -p reports
          # Build a minimal compile_commands.json for main.c
          echo '[' > compile_commands.json
          echo '  { "directory": "'"${PWD}"'", "command": "gcc -std=c17 -I. -O2 -g main.c -o main", "file": "main.c" }' >> compile_commands.json
          echo ']' >> compile_commands.json

      - name: Run Trivy scan (version pinned)
        uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808
        with:
          version: v0.64.1
          scan-type: fs
          format: sarif
          output: reports/trivy.sarif
          exit-code: 0

      - name: Run Semgrep scan (pinned Docker digest; no pip)
        # Pin the Semgrep CLI via an immutable Docker image digest
        uses: docker://semgrep/semgrep:1.127.1@sha256:85f9de554201cc891c470774bb93a7f4faf41ea198ddccc34a855b53f7a51443
        with:
          args: >
            semgrep scan
            --config p/ci
            --sarif --output reports/semgrep.sarif
            --metrics=off

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.login=${{ env.SONAR_TOKEN }}
            -Dsonar.sarifReportPaths=reports/trivy.sarif,reports/semgrep.sarif
            -Dsonar.cfamily.compile-commands=compile_commands.json
