name: SonarCloud (C)

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.c'
      - 'sonar-project.properties'
      - '.github/workflows/sonarcloud.yml'
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.c'
      - 'sonar-project.properties'
      - '.github/workflows/sonarcloud.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Default-deny
permissions:
  contents: read

jobs:
  build-and-scan:
    name: Build and analyze
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    # Elevate only what this job needs
    permissions:
      contents: read
      pull-requests: read
    env:
      BW_OUT: bw-out
    steps:
      - name: Harden runner (audit egress)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          # To block instead of audit, switch to:
          # egress-policy: block
          # allowed-endpoints: >
          #   sonarcloud.io
          #   api.sonarcloud.io
          #   binaries.sonarsource.com
          #   github.com
          #   api.github.com
          #   uploads.github.com
          #   objects.githubusercontent.com

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # v5.3.1

      - name: Wrap compile (gcc)
        run: |
          set -euxo pipefail
          mkdir -p "${BW_OUT}"
          build-wrapper-linux-x86-64 --out-dir "${BW_OUT}" sh -c 'gcc -std=c17 -I. -O2 -g main.c -o main'
        timeout-minutes: 5

      - name: SonarCloud scan
        uses: SonarSource/sonarqube-scan-action@1a6d90ebcb0e6a6b1d87e37ba693fe453195ae25 # v5.3.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BW_OUT }}/compile_commands.json

      - name: Generate SARIF from SonarCloud issues
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          set -euo pipefail
          python3 - <<'PY'
          import base64, json, os, time, urllib.parse, urllib.request, sys, pathlib

          def read_project_key():
              with open("sonar-project.properties", "r", encoding="utf-8") as f:
                  for line in f:
                      line=line.strip()
                      if line.startswith("sonar.projectKey="):
                          return line.split("=",1)[1].strip()
              raise RuntimeError("sonar.projectKey not found in sonar-project.properties")

          def get_json(url, token):
              req = urllib.request.Request(url)
              auth = base64.b64encode((token + ":").encode()).decode()
              req.add_header("Authorization", "Basic " + auth)
              with urllib.request.urlopen(req, timeout=30) as r:
                  return json.load(r)

          base = "https://sonarcloud.io"
          token = os.environ["SONAR_TOKEN"]
          project_key = read_project_key()
          print(f"Project: {project_key}")

          # Wait for the most recent CE task to finish
          for _ in range(120):  # ~6 minutes
              act = get_json(f"{base}/api/ce/activity?component={urllib.parse.quote(project_key)}&onlyCurrents=true&ps=1", token)
              tasks = act.get("tasks", [])
              if tasks:
                  tid = tasks[0]["id"]
                  ce = get_json(f"{base}/api/ce/task?id={tid}", token)
                  status = ce["task"]["status"]
                  print(f"CE status: {status}")
                  if status in ("SUCCESS", "FAILED", "CANCELED"):
                      break
              else:
                  print("No CE tasks yet")
              time.sleep(3)

          # Pull unresolved issues
          p=1; page_size=500; issues=[]
          while True:
              data = get_json(f"{base}/api/issues/search?componentKeys={urllib.parse.quote(project_key)}&resolved=false&ps={page_size}&p={p}", token)
              batch = data.get("issues", [])
              if not batch:
                  break
              issues.extend(batch)
              total = data.get("total", 0)
              if p*page_size >= total:
                  break
              p += 1

          def level(sev):
              return {"BLOCKER":"error","CRITICAL":"error","MAJOR":"warning","MINOR":"note","INFO":"note"}.get(sev,"warning")

          runs = [{
              "tool": {
                  "driver": {
                      "name": "SonarCloud",
                      "informationUri": "https://sonarcloud.io",
                      "rules": []
                  }
              },
              "results": []
          }]

          rule_index = {}
          for it in issues:
              rid = str(it.get("rule","unknown"))
              if rid not in rule_index:
                  runs[0]["tool"]["driver"]["rules"].append({
                      "id": rid,
                      "shortDescription": {"text": (it.get("message","") or "")[:120]}
                  })
                  rule_index[rid] = True
              comp = it.get("component","")
              path = comp.split(":",1)[1] if ":" in comp else comp
              tr = it.get("textRange") or {}
              sl = tr.get("startLine", 1)
              sc = (tr.get("startOffset",0) or 0) + 1
              el = tr.get("endLine", sl)
              ec = max(tr.get("endOffset", sc), sc)
              runs[0]["results"].append({
                  "ruleId": rid,
                  "level": level(it.get("severity","MAJOR")),
                  "message": {"text": it.get("message","")},
                  "locations": [{
                      "physicalLocation": {
                          "artifactLocation": {"uri": path, "uriBaseId": "PROJECT_ROOT"},
                          "region": {"startLine": sl, "startColumn": sc, "endLine": el, "endColumn": ec}
                      }
                  }],
                  "fingerprints": {"sonarIssueKey": it.get("key","")}
              })

          pathlib.Path("reports").mkdir(parents=True, exist_ok=True)
          sarif = {"version":"2.1.0", "$schema":"https://json.schemastore.org/sarif-2.1.0.json", "runs": runs}
          with open("reports/sonarcloud.sarif","w",encoding="utf-8") as f:
              json.dump(sarif, f, ensure_ascii=False)
          print(f"Wrote {len(issues)} issues to reports/sonarcloud.sarif")
          PY
        timeout-minutes: 3

      - name: Upload SARIF as artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: sonarcloud-sarif
          path: reports/sonarcloud.sarif
          retention-days: 7
          if-no-files-found: error

  upload-to-code-scanning:
    name: Publish SARIF to Code Scanning
    needs: build-and-scan
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    # Scope 'security-events: write' only here
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Harden runner (audit egress)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Download SARIF artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: sonarcloud-sarif
          path: reports

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        with:
          sarif_file: reports/sonarcloud.sarif
          category: sonarcloud
