name: SonarCloud analysis

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  security-events: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Prepare reports directory and compile_commands.json
        run: |
          mkdir -p reports
          # Build a minimal compile_commands.json for main.c
          echo '[' > compile_commands.json
          echo '  { "directory": "'"${PWD}"'", "command": "gcc -std=c17 -I. -O2 -g main.c -o main", "file": "main.c" }' >> compile_commands.json
          echo ']' >> compile_commands.json

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808 # master
        with:
          scan-type: fs
          format: sarif
          output: reports/trivy.sarif
          exit-code: 0

      - name: Install Semgrep CLI
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: python3 -m pip install --upgrade semgrep

      - name: Run Semgrep scan
        run: semgrep --config p/ci --sarif --output reports/semgrep.sarif .

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: |
            -Dsonar.login=${{ env.SONAR_TOKEN }}
            -Dsonar.sarifReportPaths=reports/trivy.sarif,reports/semgrep.sarif
            -Dsonar.cfamily.compile-commands=compile_commands.json

