name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      BW_OUT: bw-out

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure main.c exists
        run: test -f main.c

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5
        env:
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Build (wrapped)
        run: |
          mkdir -p build
          build-wrapper-linux-x86-64 --out-dir ${BW_OUT} \
            gcc -std=c17 -I. -O2 -g -c main.c -o build/main.o

      - name: Verify compile_commands.json exists
        run: |
          ls -l ${BW_OUT}
          test -s ${BW_OUT}/compile_commands.json

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            --define sonar.cfamily.compile-commands=${{ env.BW_OUT }}/compile_commands.json

      - name: Wait for analysis and export SARIF
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        run: |
          set -euo pipefail
          command -v jq >/dev/null

          mkdir -p reports

          # 1) Wait for Compute Engine to finish
          test -s .scannerwork/report-task.txt
          CE_TASK_URL="$(grep '^ceTaskUrl=' .scannerwork/report-task.txt | cut -d'=' -f2)"

          echo "Polling CE task: ${CE_TASK_URL}"
          for _ in $(seq 1 60); do
            BODY="$(curl -sS -u "$SONAR_TOKEN:" "$CE_TASK_URL")"
            STATUS="$(echo "$BODY" | jq -r '.task.status')"
            echo "CE status: $STATUS"
            if [ "$STATUS" = "SUCCESS" ]; then
              break
            elif [ "$STATUS" = "FAILED" ]; then
              echo "$BODY" | jq .
              echo "Compute Engine task failed"
              exit 1
            fi
            sleep 5
          done

          # 2) Resolve project and selector (branch vs pullRequest)
          SONAR_PROJECT_KEY="$(grep -E '^sonar\.projectKey=' sonar-project.properties | cut -d'=' -f2)"
          : "${SONAR_PROJECT_KEY:?sonar.projectKey missing in sonar-project.properties}"

          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            SELECTOR_KIND="pullRequest"
            SELECTOR_VALUE="${{ github.event.pull_request.number }}"
          else
            SELECTOR_KIND="branch"
            SELECTOR_VALUE="${GITHUB_REF_NAME:-main}"
          fi
          echo "Selector: ${SELECTOR_KIND}=${SELECTOR_VALUE}"

          # 3) Page through issues safely (URL-encoded), write NDJSON
          ALL_ISSUES="$(mktemp)"; : > "$ALL_ISSUES"
          PAGE=1; PAGE_SIZE=500
          while :; do
            # Build encoded query
            Q=( "--data-urlencode" "componentKeys=${SONAR_PROJECT_KEY}"
                "--data-urlencode" "ps=${PAGE_SIZE}"
                "--data-urlencode" "p=${PAGE}"
                "--data-urlencode" "additionalFields=_all" )
            if [ "$SELECTOR_KIND" = "pullRequest" ]; then
              Q+=( "--data-urlencode" "pullRequest=${SELECTOR_VALUE}" )
            else
              Q+=( "--data-urlencode" "branch=${SELECTOR_VALUE}" )
            fi

            # Capture response and HTTP code
            RESP="$(mktemp)"
            CODE="$(curl -sS -u "$SONAR_TOKEN:" -G "${SONAR_HOST_URL%/}/api/issues/search" "${Q[@]}" -w "%{http_code}" -o "$RESP")"
            if [ "$CODE" != "200" ]; then
              echo "SonarCloud API /api/issues/search returned HTTP $CODE"
              cat "$RESP" && rm -f "$RESP"
              exit 1
            fi

            jq -c '.issues[]' "$RESP" >> "$ALL_ISSUES" || true
            TOTAL="$(jq -r '.total // 0' "$RESP")"
            COUNT="$(wc -l < "$ALL_ISSUES" | tr -d ' ')"
            rm -f "$RESP"

            [ "$COUNT" -ge "$TOTAL" ] && break
            PAGE=$((PAGE+1))
          done

          # 4) Build SARIF 2.1.0 (using jq only)
          cat > reports/sonarcloud-findings.sarif <<'JSON'
          {
            "version": "2.1.0",
            "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
            "runs": [{
              "tool": { "driver": { "name": "SonarCloud", "informationUri": "https://sonarcloud.io", "rules": [] } },
              "results": []
            }]
          }
          JSON

          jq -s '
            def level(s):
              if s=="BLOCKER" or s=="CRITICAL" then "error"
              elif s=="MAJOR" then "warning"
              else "note" end;

            def rid: .rule;
            def path: ( .component | split(":") | if length>1 then .[1] else .[0] end );

            {
              rules: ( [ .[] | { id: rid, name: rid } ] | unique ),
              results: [ .[] | {
                ruleId: rid,
                level: level(.severity),
                message: { text: .message },
                locations: [ { physicalLocation: {
                  artifactLocation: { uri: (path | gsub("\\\\"; "/")) },
                  region: { startLine: (if (.line|type)=="number" then .line else 1 end) }
                } } ],
                properties: {
                  sonarSeverity: .severity, type: .type, effort: .effort, status: .status, key: .key
                }
              } ]
            }
          ' "$ALL_ISSUES" > reports/_tmp.json

          jq '
            .runs[0].tool.driver.rules = (input.rules | unique_by(.id)) |
            .runs[0].results = input.results
          ' reports/sonarcloud-findings.sarif reports/_tmp.json > reports/_final.sarif

          mv reports/_final.sarif reports/sonarcloud-findings.sarif
          rm -f reports/_tmp.json "$ALL_ISSUES"
          echo "Wrote reports/sonarcloud-findings.sarif"

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/sonarcloud-findings.sarif
          category: sonarcloud
