name: Trivy

on:
  push:
    # branches: [ main ]
  pull_request:
    # branches: [ main ]
  schedule:
    - cron: '27 16 * * 0'

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scan:
    name: Trivy Full Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Set up Python (optional)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.x'

      - name: Install dependencies if present
        run: |
          if [ -f requirements.txt ]; then
            python -m venv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
          fi

      - name: Run Trivy (vuln, misconfig, secret, iac)
        uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808 # master
        with:
          scan-type: fs
          scan-ref: .
          scanners: 'vuln'
          format: template
          template: '@/contrib/sarif.tpl'
          output: trivy-results.sarif
          severity: CRITICAL,HIGH,MEDIUM

      - name: Verify SARIF file
        run: |
          ls -lah .
          test -f trivy-results.sarif && echo "SARIF generated" || (echo "SARIF missing" && exit 1)

      - name: Upload Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@3c3833e0f8c1c83d449a7478aa59c036a9165498 # v3.29.11
        if: success()
        with:
          sarif_file: trivy-results.sarif
